kind: pipeline
name: default

steps:
  - name: node_modules
    image: node:10.14
    commands:
      - npm install --no-progress --quiet --unsafe-perm >  npm-install.log

  - name: develop:build
    image: node:10.14
    commands:
      - npm run build
    when:
      branch:
        - develop
        - master
        - enhancement/ci

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: log_github
    username: Drone CI
    when:
      status: [success, failure]
